version: '3.9'

volumes:
  minio_data:
    driver: local
  cloudstorage_postgres_data:
    driver: local
  redis_data:
    driver: local

services:
  postgres:
    image: postgres:15.6
    container_name: cloudstorage_postgres_container
    environment:
      - POSTGRES_USER=dbusername
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=cloudstoragedb
    ports:
      - '5430:5432'
    volumes:
      - cloudstorage_postgres_data:/data/cloudstorage


  minio:
    image: minio/minio:RELEASE.2024-02-17T01-15-57Z.fips
    container_name: cloudstorage_minio_container
    environment:
      MINIO_ROOT_USER: minio-user
      MINIO_ROOT_PASSWORD: minio-password
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio_data:/data

  redis:
    image: redis:7.2.4
    container_name: cloudstorage_redis_container
    ports:
      - "6379:6379"
    environment:
      REDIS_HOST: localhost
      REDIS_PASSWORD: redispassword
    volumes:
      - redis_data:/var/lib/redis/data