server:
  port: 8081
  servlet:
    encoding:
      enabled: true
      force: true

spring:
  devtools:
    restart:
      enabled: true
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5430/cloudstoragedb
    username: dbusername
    password: dbpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      password: redispassword

minio:
  endpoint: http://localhost:9000
  username: minio-user
  password: minio-password
  bucket: user-files

